name = "JSONPointer"
uuid = "cc3ff66e-924d-4e6b-b111-1d9960e4bba9"
authors = ["김용희 <yongheekim@devsisters.com>"]
version = "0.2.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
OrderedCollections = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
