name: Run CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop
    tags: '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.3'
          - '1' # automatically expands to the latest stable 1.x release of Julia
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: windows-latest
            version: '1'
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1