name: Coverage Report

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  job_1:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          julia-version: [1.5.0]
          julia-arch: [x86]
          os: [ubuntu-latest]
      steps:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
        - uses: julia-actions/julia-buildpkg@latest
        - uses: julia-actions/julia-runtest@latest
        - uses: julia-actions/julia-processcoverage@v1
        - name: Merge master -> gh-pages
          uses: devmasx/merge-branch@v1.3.0
          with:
            type: now
            target_branch: gh-pages
            github_token: ${{ github.token }}
        - uses: actions/upload-artifact@v2
          with:
            name: lcov
            path: lcov.info
        
  job_2:
      runs-on: ubuntu-latest
      needs: job_1
      steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lcov
          path: docs/coverage/
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v1
        with:
              dotnet-version: 3.1.302
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.6.4
        with:
            reports: 'docs/coverage/lcov.info' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
            targetdir: 'docs/coverage' # REQUIRED # The directory where the generated report should be saved.
            historydir: 'docs/coverage/history' # Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.
            reporttypes: 'HtmlInline;Badges' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
            verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
            tag: '${{ github.run_number }}_${{ github.run_id }}' # Optional tag or build version.

      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'docs/* src/*'
          message: 'Coverage Report ${{ github.sha }}'
          ref: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
